const products=[
{id:1,name:'Soleil Linen Dress',price:68000,cat:'Dresses',status:'AVAILABLE',sizes:['S','M','L'],colors:['Ivory','Sienna'],img:'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&q=85',desc:'A softly structured linen dress with a graceful silhouette, made for long lunches and late evenings.'},
{id:2,name:'Atelier Tailored Blazer',price:94000,cat:'Jackets',status:'AVAILABLE',sizes:['S','M','L','XL'],colors:['Black','Stone'],img:'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&q=85',desc:'Sharp tailoring, softened at the shoulder. A forever layer for the modern wardrobe.'},
{id:3,name:'Marrakech Silk Shirt',price:52000,cat:'Shirts',status:'LOW STOCK',sizes:['M','L'],colors:['Ochre','White'],img:'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=800&q=85',desc:'Fluid silk and a relaxed collar in a sun-washed palette.'},
{id:4,name:'The Evening Column',price:125000,cat:'Dresses',status:'PRE-ORDER',sizes:['S','M','L'],colors:['Noir'],img:'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&q=85',desc:'An elegant column gown cut for the moments that matter. Expected availability: 15 September.'},
{id:5,name:'Sunday Leather Tote',price:78000,cat:'Bags',status:'AVAILABLE',sizes:[],colors:['Cognac','Black'],img:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=85',desc:'A considered everyday carry in supple leather.'},
{id:6,name:'Studio Wide Leg Trouser',price:59000,cat:'Trousers',status:'AVAILABLE',sizes:['S','M','L','XL'],colors:['Charcoal'],img:'https://images.unsplash.com/photo-1506629905607-d9c297d38c4f?w=800&q=85',desc:'High-waisted, fluid and impeccably cut.'}
];
let cart=JSON.parse(localStorage.getItem('fm-cart')||'[]'), filter='All', query='';
// FX is supplied by the server/Edge Function and cached in Supabase; never a merchant-editable product field.
const fx=()=>{const r=Number(window.FM_FX_RATE||localStorage.getItem('fm-fx-rate'));return Number.isFinite(r)&&r>0?r:null};
const money=n=>'₦'+n.toLocaleString('en-NG');
const usd=n=>fx()?`<span class=\"usd\">≈ $${(n/fx()).toFixed(2)} USD</span>`:`<span class=\"usd unavailable\">USD price temporarily unavailable</span>`;
const fxnote=()=>fx()?`<small class=\"fxnote\">1 USD ≈ ${money(fx())}. USD prices are approximate equivalents based on the latest available rate. Final payment is in Nigerian Naira.</small>`:''; const save=()=>localStorage.setItem('fm-cart',JSON.stringify(cart));
function header(){return `<div class="top">COMPLIMENTARY DELIVERY ON ORDERS OVER ₦100,000</div><nav class="nav"><a class="logo" href="#/">Fashion Maison<small>Fashion, discovered differently.</small></a><div class="navlinks"><a href="#/shop">Shop</a><a href="#/shop?cat=New arrivals">New arrivals</a><a href="#/merchant">For your store</a></div><div class="navtools"><input class="search" placeholder="Search the collection" value="${query}" oninput="search(this.value)"><button class="icon" onclick="location.hash='#/account'">♙</button><button class="icon" onclick="location.hash='#/cart'">♧<sup class="cartdot">${cart.reduce((a,b)=>a+b.qty,0)}</sup></button></div></nav>`}
function card(p){return `<article class="product"><div class="productimg" style="background-image:url('${p.img}')" onclick="location.hash='#/product/${p.id}'"><span class="badge">${p.status}</span></div><div class="productinfo"><button class="add" onclick="add(${p.id})">＋</button><div class="productname">${p.name}</div><div class="price">${money(p.price)}<br>${usd(p.price)}</div><div class="meta">${p.cat} · ${p.sizes.join(' / ')||'One size'}</div></div></article>`}
function home(){return header()+`<main><section class="wrap hero"><div><div class="eyebrow">The new season / 01</div><h1>Fashion,<br><i>discovered</i><br>differently.</h1><p>Shop considered pieces from independent fashion houses and real stores across Nigeria.</p><button class="btn" onclick="location.hash='#/shop'">Shop the collection</button></div><div class="heroimg"></div></section><section class="wrap section"><div class="sectionhead"><div><div class="eyebrow">Curated for you</div><h2>New arrivals</h2></div><a href="#/shop" class="muted">View all →</a></div><div class="grid">${products.slice(0,4).map(card).join('')}</div></section><section class="wrap section"><div class="banner"><div><div class="eyebrow">For independent fashion businesses</div><h2>Your store,<br>beautifully online.</h2><p class="muted">Bring the pieces in your shop to a new audience.</p><button class="btn" onclick="location.hash='#/merchant'">Create your store</button></div><div></div></div></section></main>${footer()}`}
function shop(){let ps=products.filter(p=>(filter==='All'||p.cat===filter)&&(p.name+' '+p.cat+' '+p.desc).toLowerCase().includes(query.toLowerCase()));let cats=['All',...new Set(products.map(p=>p.cat))];return header()+`<main class="wrap section"><div class="sectionhead"><div><div class="eyebrow">The collection</div><h2>Shop all pieces</h2><p class="muted">${ps.length} pieces from Maison Lagos</p></div></div><div class="filters">${cats.map(c=>`<button class="pill ${filter===c?'active':''}" onclick="setFilter('${c}')">${c}</button>`).join('')}</div><div class="grid">${ps.length?ps.map(card).join(''):`<div class="empty">No pieces found.<br><button class="btn light" onclick="clearSearch()">Clear search</button></div>`}</div></main>${footer()}`}
function product(id){let p=products.find(x=>x.id==id);if(!p)return header()+'<div class="empty"><h2>Piece not found</h2></div>';return header()+`<main class="wrap detail"><div class="gallery"><div style="background-image:url('${p.img}')"></div><div style="background-image:url('${p.img}&fit=crop&sat=-20')"></div></div><div><div class="eyebrow">${p.cat} / Maison Lagos</div><h1>${p.name}</h1><div class="price">${money(p.price)}<br>${usd(p.price)}</div><p class="muted" style="line-height:1.8">${p.desc}</p><div class="option"><label>Size</label><div class="choices">${(p.sizes.length?p.sizes:['One size']).map((x,i)=>`<button class="choice ${i===0?'sel':''}">${x}</button>`).join('')}</div></div><div class="option"><label>Colour</label><div class="choices">${p.colors.map((x,i)=>`<button class="choice ${i===0?'sel':''}">${x}</button>`).join('')}</div></div><p class="meta">${p.status==='PRE-ORDER'?'Expected availability: 15 September':'Ships from Lagos · Ready in 1–3 days'}</p><button class="btn" onclick="add(${p.id})">${p.status==='PRE-ORDER'?'Pre-order now':'Add to bag'}</button><div class="section"><div class="eyebrow">The house</div><h3 class="serif">Maison Lagos</h3><p class="muted">Independent fashion, carefully selected. Pickup available in Victoria Island.</p></div></div></main>${footer()}`}
function cartPage(){let total=cart.reduce((a,i)=>a+i.price*i.qty,0);return header()+`<main class="wrap cartpanel"><div class="eyebrow">Your selection</div><h1 class="serif">Shopping bag</h1>${cart.length?cart.map(i=>`<div class="row"><span><b>${i.name}</b><br><small class="muted">${money(i.price)}</small></span><span><button onclick="change(${i.id},-1)">−</button> ${i.qty} <button onclick="change(${i.id},1)">＋</button> <button onclick="removeItem(${i.id})"> ×</button></span></div>`).join('')+`<div class="row"><b>Total</b><b>${money(total)}<br>${usd(total)}</b></div>${fxnote()}<br><button class="btn" onclick="location.hash='#/checkout'">Proceed to checkout</button>`:'<div class="empty">Your bag is waiting for something special.<br><br><button class="btn" onclick="location.hash="#/shop"">Discover pieces</button></div>'}</main>`}
function checkout(){let total=cart.reduce((a,i)=>a+i.price*i.qty,0);return header()+`<main class="checkout"><div class="eyebrow">Almost yours</div><h1 class="serif">Checkout</h1><div class="checkoutgrid"><form onsubmit="placeOrder(event)"><div class="field"><label>Full name</label><input required placeholder="Your full name"></div><div class="field"><label>Email</label><input type="email" required placeholder="you@example.com"></div><div class="field"><label>Phone number</label><input required placeholder="0800 000 0000"></div><div class="field"><label>Delivery address</label><input required placeholder="Street address, city"></div><div class="field"><label>Delivery method</label><select><option>Store pickup — Free</option><option>Local delivery — ₦3,000</option><option>Nationwide delivery — ₦7,000</option></select></div><button class="btn">Pay securely with Paystack</button></form><aside class="summary"><b>Order summary</b>${cart.map(i=>`<div class="row"><span>${i.name} × ${i.qty}</span><span>${money(i.price*i.qty)}</span></div>`).join('')}<div class="row"><b>Total</b><b>${money(total)}<br>${usd(total)}</b></div>${fxnote()}<small class="muted">You’ll be redirected to a secure payment page. Card details are never stored by Fashion Maison.</small></aside></div></main>`}
function merchant(){return header()+`<main class="admin"><div class="eyebrow">Maison Lagos / Private view</div><h1 class="serif">Good morning, Amaka.</h1><div class="side"><button class="btn" onclick="alert('Product creation requires a connected Supabase project. Run supabase-schema.sql and configure the Edge Functions described in PRODUCTION-README.md.')">＋ Add product</button><button class="btn light" onclick="alert('Store settings will be persisted once Supabase Auth and the store API are configured.')">Store settings</button></div><div class="statgrid"><div class="stat">Today's sales<b>₦284,000</b><span class="muted">↑ 18% this week</span></div><div class="stat">Orders<b>24</b><span class="muted">8 need attention</span></div><div class="stat">Products<b>42</b><span class="muted">3 low stock</span></div><div class="stat">Pre-orders<b>7</b><span class="muted">2 new this week</span></div></div><section class="section"><div class="sectionhead"><h2>Recent orders</h2><span class="muted">View all →</span></div><div class="table">${['FM-000128 · Adaeze Okafor · ₦125,000 · PRE-ORDER','FM-000127 · Zainab Bello · ₦94,000 · PAID','FM-000126 · Ifeoma James · ₦68,000 · PROCESSING'].map(x=>`<div class="row">${x}<span class="badge">View</span></div>`).join('')}</div></section></main>`}
function footer(){return `<footer class="footer"><div class="logo">Fashion Maison<small>Fashion, discovered differently.</small></div><div class="muted">Real pieces. Independent stores.<br>© 2026 Fashion Maison</div></footer>`}
function add(id){let p=products.find(x=>x.id==id),i=cart.find(x=>x.id==id);i?i.qty++:cart.push({...p,qty:1});save();render();}
function change(id,n){let i=cart.find(x=>x.id==id);i.qty+=n;if(i.qty<1)cart=cart.filter(x=>x.id!=id);save();render()} function removeItem(id){cart=cart.filter(x=>x.id!=id);save();render()} function setFilter(x){filter=x;render()} function search(x){query=x;location.hash='#/shop';render()} function clearSearch(){query='';render()} function placeOrder(e){e.preventDefault();cart=[];save();document.querySelector('main').innerHTML='<div class="empty"><div class="eyebrow">Thank you for shopping with Fashion Maison</div><h1 class="serif">Order confirmed.</h1><p>Your order <b>FM-000129</b> has been received. A confirmation is on its way.</p><button class="btn" onclick="location.hash=\'#/shop\'">Continue shopping</button></div>'}
function render(){let h=location.hash||'#/';let content=h==='#/'?home():h.startsWith('#/shop')?shop():h==='#/cart'?cartPage():h==='#/checkout'?checkout():h==='#/merchant'?merchant():h.startsWith('#/product/')?product(h.split('/')[2]):home();document.getElementById('app').innerHTML=content}window.addEventListener('hashchange',render);render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');