-- Fashion Maison production schema (Supabase/PostgreSQL)
create extension if not exists "pgcrypto";
create type public.user_role as enum ('customer','merchant','admin');
create type public.product_status as enum ('AVAILABLE','LOW STOCK','OUT OF STOCK','PRE-ORDER');
create type public.order_status as enum ('pending','paid','processing','ready','shipped','delivered','cancelled','pre-order');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, role user_role not null default 'customer', full_name text, phone text, avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.merchants (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references profiles(id) on delete cascade, created_at timestamptz not null default now());
create table public.stores (id uuid primary key default gen_random_uuid(), merchant_id uuid not null unique references merchants(id) on delete cascade, slug text not null unique, name text not null, description text, logo_url text, cover_url text, address text, phone text, whatsapp text, delivery_options jsonb not null default '[]', opening_hours jsonb not null default '{}', approved boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), store_id uuid references stores(id) on delete cascade, name text not null, unique(store_id,name));
create table public.products (id uuid primary key default gen_random_uuid(), store_id uuid not null references stores(id) on delete cascade, category_id uuid references categories(id) on delete set null, name text not null, description text, price numeric(12,2) not null check(price>=0), status product_status not null default 'AVAILABLE', expected_availability date, published boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.product_images (id uuid primary key default gen_random_uuid(), product_id uuid not null references products(id) on delete cascade, storage_path text not null, sort_order int not null default 0, created_at timestamptz not null default now());
create table public.product_variants (id uuid primary key default gen_random_uuid(), product_id uuid not null references products(id) on delete cascade, size text, color text, sku text, price numeric(12,2), unique(product_id,size,color));
create table public.inventory (variant_id uuid primary key references product_variants(id) on delete cascade, quantity int not null default 0 check(quantity>=0), reserved int not null default 0 check(reserved>=0), updated_at timestamptz not null default now());
create table public.carts (id uuid primary key default gen_random_uuid(), customer_id uuid not null unique references profiles(id) on delete cascade, updated_at timestamptz not null default now());
create table public.cart_items (id uuid primary key default gen_random_uuid(), cart_id uuid not null references carts(id) on delete cascade, variant_id uuid not null references product_variants(id), quantity int not null check(quantity>0), unique(cart_id,variant_id));
create table public.addresses (id uuid primary key default gen_random_uuid(), customer_id uuid not null references profiles(id) on delete cascade, label text, line1 text not null, city text not null, state text, phone text, created_at timestamptz not null default now());
create table public.orders (id uuid primary key default gen_random_uuid(), order_number text not null unique, customer_id uuid not null references profiles(id), store_id uuid not null references stores(id), status order_status not null default 'pending', subtotal numeric(12,2) not null, delivery_fee numeric(12,2) not null default 0, total numeric(12,2) not null, delivery_method text, delivery_address jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references orders(id) on delete cascade, product_id uuid not null references products(id), variant_id uuid references product_variants(id), product_name text not null, quantity int not null check(quantity>0), unit_price numeric(12,2) not null, is_preorder boolean not null default false);
create table public.payments (id uuid primary key default gen_random_uuid(), order_id uuid not null unique references orders(id) on delete cascade, provider text not null default 'paystack', reference text unique, status text not null default 'pending', amount numeric(12,2) not null, paid_at timestamptz, provider_payload jsonb, created_at timestamptz not null default now());
create table public.preorders (id uuid primary key default gen_random_uuid(), order_id uuid not null unique references orders(id) on delete cascade, expected_availability date, status text not null default 'placed', created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references profiles(id) on delete cascade, type text not null, title text not null, body text, read_at timestamptz, created_at timestamptz not null default now());
create table public.exchange_rates (id uuid primary key default gen_random_uuid(), base_currency char(3) not null, quote_currency char(3) not null, rate numeric(20,8) not null check(rate>0), source text not null, rate_type text not null default 'market', effective_at timestamptz not null, expires_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index exchange_rates_current on exchange_rates(base_currency,quote_currency,effective_at desc); create index exchange_rates_valid on exchange_rates(base_currency,quote_currency,expires_at,effective_at desc); alter table exchange_rates enable row level security; create policy "public can read current fx" on exchange_rates for select using (base_currency='USD' and quote_currency='NGN');
create or replace view public.current_usd_ngn_rate as select distinct on (base_currency,quote_currency) id,base_currency,quote_currency,rate,source,rate_type,effective_at,created_at from public.exchange_rates where base_currency='USD' and quote_currency='NGN' and (expires_at is null or expires_at>now()) order by base_currency,quote_currency,effective_at desc;
create index products_store_published on products(store_id,published); create index products_search on products using gin(to_tsvector('simple',coalesce(name,'')||' '||coalesce(description,'')));

alter table profiles enable row level security; alter table merchants enable row level security; alter table stores enable row level security; alter table products enable row level security; alter table product_images enable row level security; alter table carts enable row level security; alter table cart_items enable row level security; alter table orders enable row level security; alter table order_items enable row level security; alter table payments enable row level security; alter table addresses enable row level security; alter table notifications enable row level security;
create policy "public published products" on products for select using (published=true);
create policy "merchant owns products" on products for all using (exists(select 1 from stores s join merchants m on m.id=s.merchant_id where s.id=products.store_id and m.user_id=auth.uid()));
create policy "users own profile" on profiles for all using (id=auth.uid());
create policy "users own cart" on carts for all using (customer_id=auth.uid());
create policy "users own orders" on orders for select using (customer_id=auth.uid() or exists(select 1 from stores s join merchants m on m.id=s.merchant_id where s.id=orders.store_id and m.user_id=auth.uid()));
create policy "users own addresses" on addresses for all using (customer_id=auth.uid());
create policy "users own notifications" on notifications for select using (user_id=auth.uid());
-- Inventory decrement, order creation, and Paystack verification must run in trusted server-side Edge Functions.
